### ISSUE TITLE
empty error in exception urllib2.HTTPError

### ISSUE THREAD

**Issue by vinavfx** [vinavfx/nuke_comfyui#3]
Hello，
Thank you for your nice work.
When I use the submit of the SaveImage node, the following error message pops up:

Traceback (most recent call last):
  File "C:\Users/About/.nuke\nuke_comfyui\src\connection.py", line 31, in send_request
    error = json.loads(e.read())
  File "C:\Program Files\Nuke15.0v4\python310.zip\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Program Files\Nuke15.0v4\python310.zip\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Program Files\Nuke15.0v4\python310.zip\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

Then Nuke crashed.

_Originally posted by @DerickYau in https://github.com/vinavfx/nuke_comfyui/issues/1#issuecomment-2068471169_

**Comment by vinavfx** [comment]
This sends a message for the error: https://github.com/vinavfx/nuke_comfyui/commit/20a9ff73a5caea38f6fe30a302225bd993af2c6e
will not solve that error because it is empty and I don't know what it could be.
